'use strict';

exports.BattlePokedex = {
  charish: {
        num: 736,
        species: "Charish",
        types: ["Fire","Dark"],
        baseStats: {hp: 55, atk: 70, def: 65, spa: 82, spd: 70, spe: 31},
        abilities: {0: "Flare Boost"},
        evos: ["charkol"],
	},
  charkol: {
        num: 324,
        species: "Charkol",
        types: ["Fire","Dark"],
        baseStats: {hp: 90, atk: 112, def: 81, spa: 109, spd: 75, spe: 53},
        abilities: {0: "Fire Resistance"},
        evos: ["N/A"],
        prevo: "charish",
  },
  calibri: {
        num: 640,
        species: "Calibri",
        types: ["Fighting"],
        baseStats: {hp: 80, atk: 140, def: 85, spa: 40, spd: 100, spe: 40},
        abilities: {0: "Speed Boost"},
        evos: ["N/A"],
        prevo: "N/A",
  },
  sudowoodomega: {
        num: 185,
        species: "Sudowoodo-Mega",
        types: ["Rock"],
        baseStats: {hp: 70, atk: 115, def: 135, spa: 15, spd: 85, spe: 40},
        abilities: {0: "Skill Link"},
        evos: ["N/A"],
        prevo: "Sudowoodo",
  },
  charizardmegaz: {
        num: 6,
        species: "Charizard-Mega-Z",
        types: ["Ground","Fire"],
        baseStats: {hp: 78, atk: 94, def: 118, spa: 99, spd: 135, spe: 96},
        abilities: {0: "Arena Trap"},
        evos: ["N/A"],
        prevo: "Charizard",
  },
  kingleralola: {
        num: 99,
        species: "Kingler-Alola",
        types: ["Water","Rock"],
        baseStats: {hp: 55, atk: 150, def: 100, spa: 105, spd: 100, spe: 30},
        abilities: {0: "Boulder Shield"},
        evos: ["N/A"],
        prevo: "N/A",
  },
  grumpigalola: {
        num: 326,
        species: "Grumpig-Alola",
        types: ["Psychic","Grass"],
        baseStats: {hp: 99, atk: 70, def: 161, spa: 70, spd: 131, spe: 81},
        abilities: {0: "Weak Armor"},
        evos: ["N/A"],
        prevo: "N/A",
  },
  wolvim: {
        num: 261,
        species: "Wolvim",
        types: ["Dark"],
        baseStats: {hp: 25, atk: 70, def: 31, spa: 70, spd: 44, spe: 61},
        abilities: {0: "Run Away"},
        evos: ["Wolvamp"],
        prevo: "N/A",
  },
  wolvamp: {
        num: 262,
        species: "Wolvamp",
        types: ["Dark"],
        baseStats: {hp: 40, atk: 101, def: 53, spa: 99, spd: 49, spe: 92},
        abilities: {0: "Intimidate", H: "Dark Aura"},
        evos: ["Wolvama"],
        prevo: "Wolvim",
  },
  wolvama: {
        num: 59,
        species: "Wolvama",
        types: ["Dark","Fire"],
        baseStats: {hp: 51, atk: 130, def: 72, spa: 119, spd: 72, spe: 126},
        abilities: {0: "Dark Aura"},
        evos: ["Does Not Evolve"],
        prevo: "Wolvamp",
  },
  draconeel: {
        num: 1000,
        species: "Draconeel",
        types: ["Dragon"],
        baseStats: {hp: 80, atk: 40, def: 60, spa: 42, spd: 50, spe: 20},
        abilities: {0: "Clear Body"},
        evos: ["Dracotanium"],
        prevo: "N/A",
  },
  dracotanium: {
        num: 1001,
        species: "Dracotanium",
        types: ["Dragon","Steel"],
        baseStats: {hp: 145, atk: 65, def: 88, spa: 71, spd: 88, spe: 40},
        abilities: {0: "Clear Body", H: "Multiscale"},
        evos: ["Does Not Evolve"],
        prevo: "Draconeel",
  },
  dracotaniummega: {
        num: 1002,
        species: "Dracotanium-Mega",
        types: ["Dragon","Fire"],
        baseStats: {hp: 145, atk: 95, def: 99, spa: 101, spd: 108, spe: 50},
        abilities: {0: "Multiscale"},
        evos: ["Dracotanium"],
        prevo: "N/A",
  },
  
};
